main = ".open-next/worker.js"
name = "beta-trading-sto"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
[limits]
cpu_ms = 300000
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[[routes]]
pattern = "beta.unitoken.trade"
custom_domain = true
[[d1_databases]]
binding = "unitoken_db"
database_name = "unitoken_db"
database_id = "02704177-c811-4132-92e4-622f955a7ae8"
[vars]
N_PARTITIONS = "1"
[[queues.producers]]
  binding = "input_part_0"
  queue = "input-part-0"
  delivery_delay = 0