FROM rust:1.70 AS builder
WORKDIR /app
COPY apps/backend . 
RUN cargo build --release

FROM gcr.io/distroless/cc-debian11
COPY --from=builder /app/target/release/trading-sto-backend /app/trading-sto-backend
CMD ["/app/trading-sto-backend"]
