FROM node:20-alpine AS base
WORKDIR /app
COPY apps/web/package*.json ./
RUN npm ci

FROM base AS builder
COPY apps/web . 
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
CMD ["npm", "start"]
